name: Sphinx Documentation
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build-sphinx-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[docs]
      - name: Run Sphinx build
        run: |
          sphinx-build -b html docs/source/ docs/build/
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-sphinx-html
          path: docs/build/