name: Python and Conda Packaging
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build-python-dist:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build
      - name: Build package
        run: python -m build
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-python
          path: dist
  build-conda-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: build-env
          python-version: "3.11"
          auto-update-conda: true
          auto-activate-base: false
          miniforge-version: "latest"
          channels: conda-forge,default
          use-mamba: true
      - name: Install conda-build and conda-index
        run: mamba install -c conda-forge conda-build conda-index
        shell: bash -el {0}
      - name: Build Conda package (using rattler-build)
        uses: prefix-dev/rattler-build-action@v0.2.6
        with:
          recipe-path: recipe/meta.yaml
          upload-artifact: false
      - name: Clean conda build directory
        run: |
          rm -rf output/bld
          rm -rf output/src_cache
          rm -rf output/linux-64
      - name: Index conda build directory
        run: |
          python -m conda_index --channeldata --rss ./output
        shell: bash -el {0}
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-conda
          path: output/