name: Build and Deploy Site
on:
  workflow_dispatch:
  workflow_call:

jobs:
  run-packaging:
    uses: ./.github/workflows/packaging.yaml
  run-documentation:
    uses: ./.github/workflows/documentation.yaml
  build-and-deploy:
    needs: [run-packaging, run-documentation]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Sphinx documentation artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-sphinx-html
          path: ./docs
      - name: Download Python package artifact
        uses: actions/download-artifact@v4
        with:
          name: package-python
          path: ./dist-python
      - name: Download Conda package artifact
        uses: actions/download-artifact@v4
        with:
          name: package-conda
          path: ./dist-conda
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
